### ISSUE TITLE
Cannot properly import the angular package

### ISSUE THREAD

**Issue by Ponchia** [webalys-hq/packages-issues#1]
**Environment**

_I'm running on_ : <br/>
- [X] macOS (version: 10.15.7 ) <br/>
- [ ] windows (verion: ) <br/>
- [ ] other - please specify <br/>

_Node environment_  <br/>
Node : v13.8.0<br/>
NPM version : 6.14.7<br/>
Yarn version (if applicable) :  <br/>

_Package version_  <br/>
Wrapper : 0.7.3
Icons : 0.6.1

**Describe the bug**

Cannot import and use the `@streamlinehq/streamline-icons-angular`

**Error logged in the console:**
I've followed the tutorials: 
-  https://www.notion.so/Setting-up-project-token-management-for-NPM-d0d148cbc93d4813aeeda96699c6c366
-  https://www.notion.so/Using-Streamline-Icons-with-the-Angular-63a40e1935014ce68f35a981e7018edf

When I try to import the module as explained in the doc I get the following error.
```
import {StreamlineIconModule} from 'streamline-icons';
// Cannot find module 'streamline-icons' or its corresponding type declarations.
```

If I try to import directly from `dist` like this:
```
import {StreamlineIconModule} from '@streamlinehq/streamline-icons-angular/dist/streamline-icons';
// No errors on compile time or from Angular, but I get a tView is not defined error on the browser
```

By deleting the node_modules folder inside the `@streamlinehq/streamline-icons-angular` I'm able to have it working while serving angular and while hosted locally. But from the host, I cannot use this approach because the modules are downloaded each build

**Expected behaviour:** 
It should work without having to modify anything

**Bug report checklist**

- [X] I have read the troubleshooting guide on Streamline Documentation
- [X] I have filled out as much of the above information as I can
- [X] I have searched for existing issues and to the best of my knowledge this is not a duplicate

I want to add a huge thanks for adding the possibility to report bugs here on Github.

**Comment by Ponchia** [comment]
No update on Ivy compatibility?

**Comment by jenyashvartsman** [comment]
Have the same issue. Any updates on this?

**Comment by cbrwizard** [comment]
Hello @Ponchia, @jenyashvartsman, thanks for raising this issue! I am now responsible for all issues related to Streamline npm packages and I will go through each of them in the following days. I assume you're still experiencing this issue, right?

**Comment by jenyashvartsman** [comment]
@cbrwizard, still have the issue. using 0.7.3 version

**Comment by cbrwizard** [comment]
Hey, we have just released our wrapper for angular as open source, while we kept all icon packages as private. Angular package can be downloaded at https://github.com/webalys-hq/streamline-wrapper-angular.
Could you please try using the new package for your project and check if helps? Thank you!

**Comment by Ponchia** [comment]
@cbrwizard 
Finally had the time to test it and I can confirm now everything seems to be working as expected!
Thanks!

**Comment by jenyashvartsman** [comment]
@cbrwizard , sorry for the late response. Tested as well, working good.
Thanks

**Comment by cbrwizard** [comment]
I'm glad to hear that! If you have any more issues let's open them in the new open source repo, while this is going to be deprecated.
