### ISSUE TITLE
If 'streamline-icon' is an Angular component, then verify that it is part of this module.

### ISSUE THREAD

**Issue by lucky0007** [webalys-hq/packages-issues#2]
**Environment**

_I'm running on_ : <br/>
- [ ] windows (verion: ) <br/>

_Node environment_  <br/>
Node :  v14.5.0<br/>
NPM version : 6.14.5<br/>

**Describe the bug**
 Please let me know why it is appearing when I try to run the ng serve command. It shows the errors. 'streamline-icons' is not a known element:
If 'streamline-icon' is an Angular component, then verify that it is part of this module.
If 'streamline-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Error loggued in console:**
<streamline-icon [icon]="icon"></streamline-icon>
  src/app/app.component.ts:11:16
    11   templateUrl: './app.component.html',              
    Error occurs in the template of component AppComponent.
src/app/app.component.html:2:18 - error NG8002: Can't bind to 'icon' since it isn't a known property of 'streamline-icon'.
**1. If 'streamline-icon' is an Angular component and it has 'icon' input, then verify that it is part of this module.
2. If 'streamline-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Don't forget to obfuscate the token if present)

![image](https://user-images.githubusercontent.com/12132160/97262447-daa5ac00-1846-11eb-9862-592bc14e7895.png)

**Bug report checklist**

- [x] I have read the troubleshooting guide on Streamline Documentation
- [ ] I have filled out as much of the above information as I can
- [ ] I have searched for existing issues and to the best of my knowledge this is not a duplicate

**Comment by csauvage** [comment]
It seems to be linked to an ivy (Angular rendering and compiler) issue. Can you please confirm your angular version ? Thanks.

**Comment by lucky0007** [comment]
We are using Angular10.

**Comment by lucky0007** [comment]
Did you check the issue?


Thanks
Lokendra

**Comment by cbrwizard** [comment]
Hello @lucky0007, thanks for raising this issue! I am now responsible for all issues related to Streamline npm packages and I will go through each of them in the following days. I assume you're still experiencing this issue, right?

**Comment by cbrwizard** [comment]
Hey, we have just released our wrapper for angular as open source, while we kept all icon packages as private. Angular package can be downloaded at https://github.com/webalys-hq/streamline-wrapper-angular.
Could you please try using the new package for your project and check if helps? Thank you!

**Comment by cbrwizard** [comment]
I'll count this as fixed as other issues people used to have with installing Angular wrapper are gone now
