### ISSUE TITLE
Cannot install Angular package

### ISSUE THREAD

**Issue by elrabelo** [webalys-hq/packages-issues#3]
**Environment**

_I'm running on_ : <br/>
- [X] macOS (version: 10.15.7) <br/>
- [ ] windows (version: ) <br/>
- [ ] other - please specify <br/>

_Node environment_  <br/>
Node : v14.15.0<br/>
NPM version : 6.14.8<br/>
Yarn version (if applicable) :  <br/>

_Package version_  <br/>
Wrapper : 
Icons : 

**Describe the bug**
Cannot install package on `npm install —-save @streamlinehq/streamline-icons-angular`

**Error loggued in console:**
`400 Bad Request - GET https://npm.cloudsmith.io/streamlinehq/streamline-icons/@streamlinehq%2fstreamline-icons-angular - Response from https://registry.npmjs.com/@streamlinehq%2Fstreamline-icons-angular: Not found`

**Expected behavior:** 
Install package and add it properly on package.json.

**Bug report checklist**

- [X] I have read the troubleshooting guide on Streamline Documentation
- [X] I have filled out as much of the above information as I can
- [X] I have searched for existing issues and to the best of my knowledge this is not a duplicate

**Comment by csauvage** [comment]
Hi @elrabelo we've done a bunch of updates regarding tokens, can you tell us if it's working ?

**Comment by elrabelo** [comment]
Hi @csauvage! Thanks for the return.
No, not yet. Still the same problem.
When I look at Token Limitations it recognizes that I added the `.npmrc`, but when I try to install using npm I'm getting the error 400 (Bad Request - Not found).

**Comment by elrabelo** [comment]
I tried to install the icon package too: `npm install --save @streamlinehq/streamline-light`, this works.
Just the library `npm install --save @streamlinehq/streamline-icons-angular` is not working.

**Comment by cbrwizard** [comment]
Hello @elrabelo, thanks for raising this issue! I am now responsible for all issues related to Streamline npm packages and I will go through each of them in the following days. I assume you're still experiencing this issue, right?

**Comment by elrabelo** [comment]
Hi @cbrwizard! Thank you for getting in touch.
Yes, same issue yet.

**Comment by ATBO** [comment]
We are also experiencing this issue.

**Comment by cbrwizard** [comment]
Hey, we have just released our wrapper for angular as open source, while we kept all icon packages as private. Angular package can be downloaded at https://github.com/webalys-hq/streamline-wrapper-angular.
Could you please try using the new package for your project and check if helps? Thank you!

**Comment by elrabelo** [comment]
Thank you @cbrwizard. It worked that way.

**Comment by cbrwizard** [comment]
@elrabelo I'm glad to hear that!
Let's wait until @ATBO confirms that this worked for them as well

**Comment by cbrwizard** [comment]
Since people in the other issue https://github.com/webalys-hq/packages-issues/issues/1 no longer have this problem as well I conclude that this issue is completed as well. If you have any more issues let's open them in the new open source repo, while this is going to be deprecated.
